spring:
  profiles:
    active: local

---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password:
      driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

---
spring:
  profiles: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/spring_batch
      username: root
      password: mysql
      driver-class-name: com.mysql.jdbc.Driver

---
spring:
  profiles: postgres
  datasource:
    hikari:
      maximum-pool-size: 4
    password: pgadmin
    url: jdbc:postgresql://localhost:5432/kalpha
    username: pgadmin
