spring:
  profiles:
    active: postgres
  jpa:
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true
    properties:
      hibernate:
        format_sql: true
    show-sql: true
server:
  port: 8080
logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace
---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password:
      driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
---
spring:
  profiles: postgres
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/kalpha
      username: pgadmin
      password: pgadmin
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none

